---
- name: Install apache_exporter for Prometheus
  hosts: srvweb
  become: yes
  remote_user: tux
  tasks:
    - name: create a apache_exporter group
      group:
        name: apache_exporter
        state: present
    - name: create a apache_exporter user
      user:
        name: apache_exporter
        state: present
        shell: /bin/false
        groups: apache_exporter
        system: yes
    - name: installation de wget
      apt:
        name: wget
        update_cache: yes
    - name: Download apache_exporter.tar.gz
      command: wget  https://github.com/Lusitaniae/apache_exporter/releases/download/v0.11.0/apache_exporter-0.11.0.linux-amd64.tar.gz
    - name: Extract apache_exporter.tar.gz
      command: tar -zxf apache_exporter-0.11.0.linux-amd64.tar.gz
    - name: Install apache_exporter
      command: install apache_exporter-0.11.0.linux-amd64/apache_exporter /usr/local/bin/
    - name: creation du fichier de service pour apache_exporter
      file:
        path: /etc/systemd/system/apache_exporter.service
        state: touch
    - blockinfile:
        path: /etc/systemd/system/apache_exporter.service
        block: |
          [Unit]
          Description=Prometheus Apache Exporter
          Wants=network.target
          After=network.target
          [Service]
          User=apache_exporter
          Group=apache_exporter
          Type=simple
          ExecStart=/usr/local/bin/apache_exporter
          Restart=always
          [Install]
          WantedBy=multi-user.target
    - name: Reload Daemon
      command: systemctl daemon-reload
    - name: Start and enable apache_exporter service
      service:
        name: apache_exporter
        state: started
        enabled: yes
